//st-mssql-tools: Autogenerated Module
'use strict';
let settings = require('../../mssql.json'),
    MSSQL = require('st-mssql-proc'),
    DB = new MSSQL(settings.databases.{{database}});

class {{table}} {
    constructor(e) {
        {% for col in columns %}
        this.{{col.name}} = e.{{col.name}};{% endfor %}
    }
    save() {
        return DB.call('usp_{{table}}_post', { p_Records: this });
    }
    static saveList(records) {
        return DB.call('usp_{{table}}_post', { p_Records: records });
    }
    static all() {
        return DB.call('usp_{{table}}_get', { p_{{identity.name}}: null });
    }
    static byId(id) {
        return DB.call('usp_{{table}}_get', { p_{{identity.name}}: id });
    }
}

module.exports = {{table}};
